package com.example.mvp.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.mvp.bean.data;

import com.example.mvp.db.dataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dataDaoConfig;

    private final dataDao dataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dataDaoConfig = daoConfigMap.get(dataDao.class).clone();
        dataDaoConfig.initIdentityScope(type);

        dataDao = new dataDao(dataDaoConfig, this);

        registerDao(data.class, dataDao);
    }
    
    public void clear() {
        dataDaoConfig.clearIdentityScope();
    }

    public dataDao getDataDao() {
        return dataDao;
    }

}
